defaults:
  - model: pcqm4m
  - _self_

root: .
checkpoint: null

# Training
seed: 0
lr: 2e-4
min_lr: 0
weight_decay: 0.1
gradient_norm: 5.0
batch_size: 256
num_steps: 2e6
num_warmup_steps: 6e4
num_workers: 8
log_after: 100
val_after: 13198

# Misc
wandb_project: null
wandb_entity: null
wandb_name: null

